// data.js — all the content the extension ships with.
// Edit freely: add glossary terms, tips, or checklist items here.

const WCA_CHECKLIST = [
  {
    group: "Documents",
    items: [
      "Passport / ID",
      "Cruise boarding documents",
      "Travel insurance papers",
      "Credit cards & some cash",
      "Printed shore excursion tickets",
    ],
  },
  {
    group: "Essentials",
    items: [
      "Medications (in carry-on!)",
      "Sunscreen & after-sun lotion",
      "Sunglasses & hat",
      "Seasickness remedies",
      "Lanyard for cruise card",
      "Magnetic hooks (cabin walls are metal)",
      "Reusable water bottle",
      "Non-surge power strip / USB hub",
    ],
  },
  {
    group: "Clothing",
    items: [
      "Formal night outfit",
      "Swimwear (pack 2)",
      "Comfortable walking shoes",
      "Light jacket for windy decks",
      "Day bag for port stops",
    ],
  },
  {
    group: "Tech",
    items: [
      "Phone charger & power bank",
      "Camera / GoPro",
      "Downloaded offline maps & music",
    ],
  },
];

const WCA_GLOSSARY = [
  ["Aft", "The rear section of the ship."],
  ["All aboard time", "The deadline to be back on the ship in port — usually 30–60 minutes before departure. The ship will not wait!"],
  ["Back-to-back", "Two consecutive cruises taken on the same ship."],
  ["Berth", "A bed on a ship, or the dock space where a ship parks."],
  ["Bow", "The front of the ship."],
  ["Bridge", "The command center from which the captain navigates the ship."],
  ["Cabin / Stateroom", "Your room on the ship."],
  ["Debarkation / Disembarkation", "The process of leaving the ship at the end of a cruise."],
  ["Draft", "How deep the ship sits below the waterline — determines which ports it can enter."],
  ["Embarkation", "Boarding the ship on day one."],
  ["Galley", "The ship's kitchen."],
  ["Gangway", "The ramp or stairs you use to get on and off the ship."],
  ["Guarantee cabin", "A discounted booking where the cruise line picks your exact cabin for you."],
  ["Knot", "Speed at sea: 1 knot = 1.85 km/h (1.15 mph)."],
  ["Lido deck", "The pool deck, usually with casual buffet dining."],
  ["Muster drill", "The mandatory safety briefing before sailing, held at your muster station."],
  ["Muster station", "Your assigned assembly point in case of emergency."],
  ["Port (side)", "The left side of the ship when facing forward."],
  ["Port of call", "A destination where the ship stops during the cruise."],
  ["Purser", "The officer in charge of onboard accounts — today usually 'Guest Services'."],
  ["Repositioning cruise", "A one-way cruise moving a ship between regions — often longer and cheaper."],
  ["Sea day", "A day spent entirely at sea with no port stop."],
  ["Ship time", "The time zone the ship runs on — may differ from the port's local time. Always follow ship time."],
  ["Shore excursion", "A guided tour or activity booked at a port of call."],
  ["Starboard", "The right side of the ship when facing forward."],
  ["Stern", "The rearmost part of the ship."],
  ["Tender", "A small boat that shuttles passengers ashore when the ship anchors off the coast."],
];

const WCA_TIPS = [
  "Arrive at your departure city at least one day early — never fly in on embarkation day.",
  "Pack a carry-on with swimwear, medications and documents: checked bags can take hours to reach your cabin.",
  "Book popular shore excursions and specialty dining as soon as booking opens — they sell out.",
  "Always run on SHIP TIME in port, not local time. Set your watch to the ship.",
  "Magnetic hooks are the #1 cabin hack — walls and ceilings are metal.",
  "Surge-protected power strips are banned on ships; bring a non-surge strip or USB hub instead.",
  "Muster drill is mandatory — do it early and you'll skip the queues.",
  "Do the math on drink packages: they usually pay off around 5–6 drinks per day.",
  "Book excursions with a guarantee to return you to the ship on time — the ship waits for its own tours, not for you.",
  "Cabins midship on lower decks feel the least motion if you're prone to seasickness.",
  "Green apples and ginger from the buffet are classic seasickness helpers.",
  "Put your phone in airplane mode at sea — maritime roaming charges are brutal.",
  "The first sea day morning is the quietest time to enjoy the pool.",
  "Check your onboard account every couple of days to catch billing surprises early.",
  "Travel insurance with medical evacuation cover is essential — ship medical care is expensive.",
  "Take photos of your luggage and cruise card — it speeds up any lost-item report.",
  "Use the stairs for a few decks — elevators are the biggest time sink on busy days.",
  "On formal night, book your photos before dinner when you're freshest.",
  "Bring small bills for crew tips and port vendors.",
  "Room service breakfast on your balcony beats the buffet crowds on port mornings.",
  "Learn 'port' from 'starboard': port and left both have four letters.",
  "The daily planner delivered to your cabin is gold — highlight what you want to do each night before.",
  "Refillable water bottles save money: fill at the buffet station before excursions.",
  "Laundry deals often appear mid-cruise: a stuff-the-bag special can rescue an overpacked suitcase.",
  "Book your next cruise while on board — future cruise desks offer extra onboard credit.",
  "Sail-away from the top deck is a moment you'll remember: get up there 30 minutes before departure.",
  "Motion-sickness patches work best applied hours BEFORE you feel ill.",
  "Keep valuables in the cabin safe — set a code you'll actually remember.",
  "Walk the whole ship on day one; knowing the layout saves hours over the week.",
  "The crew knows everything: ask your cabin steward for the best-kept secrets on board.",
];
