// extra.js — Ships, Itinerary planner and Community content.
// Merged into I18N at boot (see app.js). Ship data is language-neutral.

const WCA_EXTRA = {
en: {
  ui: {
    navShips: "Ships", navAcademy: "Academy", navCommunity: "Community",
    chipShips: "🚢 Ships & lines", chipItin: "🗺 Itinerary planner", chipCommunity: "🤝 Community",
    shipsTitle: "🚢 Cruise Lines & Ships",
    shipsLead: "Who sails where — the major cruise lines and their famous ships.",
    linesTitle: "The major cruise lines",
    fleetTitle: "Famous ships",
    shipSearchPh: "Search ships or cruise lines…",
    thShip: "Ship", thLine: "Cruise line", thYear: "Year", thGT: "Gross tonnage",
    thGuests: "Guests", thRegion: "Typical region",
    shipsNote: "Figures are approximate (guests at double occupancy). Ships move between regions by season — check the line's website for current deployments.",
    shipsNone: "No ships found.",
    itinTitle: "🗺 My Itinerary",
    itinLead: "Build your own day-by-day plan — port stops, arrival and all-aboard times. Saved on this device.",
    itPort: "Port", itDate: "Date", itArr: "Arrive", itDep: "All aboard", itNotes: "Notes",
    itPortPh: "e.g. Cozumel, Mexico", itNotesPh: "excursion, meeting point…",
    itAdd: "Add stop", itEmpty: "No stops yet — add your first port above.",
    itDay: "Day",
    acGlossary: "📖 Glossary", acQuiz: "🎓 Quiz",
    academyTitle: "🎓 Academy",
    communityTitle: "🤝 Community",
    communityLead: "You're not sailing alone. Join the World Cruise Academy community.",
    joinTitle: "Join the conversation",
    joinWhatsApp: "WhatsApp Group", joinWhatsAppDesc: "Daily chat for crew & cruise lovers",
    joinTelegram: "Telegram Channel", joinTelegramDesc: "News, tips and job alerts",
    joinFacebook: "Facebook Group", joinFacebookDesc: "Photos, stories and Q&A",
    joinSoon: "Link coming soon",
    storiesTitle: "Stories from the sea",
    sampleTag: "Example story",
    shareTitle: "Share your story",
    shareDesc: "Worked on ships? Sailed somewhere unforgettable? Send us your story and we may feature it here.",
    shareBtn: "✉️ Send your story",
  },
  regions: {
    caribbean: "Caribbean", mediterranean: "Mediterranean", europe: "Northern Europe",
    asia: "Asia", alaska: "Alaska", bahamas: "Bahamas & Florida", world: "World voyages",
  },
  lines: [
    { key: "rci", blurb: "The biggest ships afloat — resort-style giants of the Oasis and Icon classes.", regions: ["caribbean", "mediterranean"] },
    { key: "carnival", blurb: "The 'Fun Ships' — casual, lively cruising, big in North America.", regions: ["caribbean", "bahamas"] },
    { key: "msc", blurb: "Fast-growing European line with a huge modern fleet, strong in the Med and Gulf.", regions: ["mediterranean", "caribbean"] },
    { key: "ncl", blurb: "Freestyle cruising — no fixed dining times, resort feel.", regions: ["caribbean", "europe", "alaska"] },
    { key: "princess", blurb: "Classic premium cruising, famous for Alaska seasons.", regions: ["alaska", "caribbean", "world"] },
    { key: "celebrity", blurb: "Modern premium line with design-forward Edge-class ships.", regions: ["caribbean", "mediterranean", "alaska"] },
    { key: "costa", blurb: "Italian style at sea — Mediterranean heartland.", regions: ["mediterranean"] },
    { key: "disney", blurb: "Family cruising with Disney character magic on board.", regions: ["bahamas", "caribbean"] },
    { key: "cunard", blurb: "Ocean-liner tradition — transatlantic crossings and world voyages.", regions: ["world", "europe"] },
  ],
  stories: [
    { name: "Made, Bali 🇮🇩", role: "Bar waiter, 6 contracts", text: "My first contract I was terrified of the drills and the English tests. By the third contract I was training the new joiners. Ship life is hard work — but I built a house at home from my savings, and I've seen 41 countries." },
    { name: "Sarah, Manchester 🇬🇧", role: "First-time guest", text: "I almost cancelled because I was scared of seasickness. Midship cabin, patches on early, and honestly — I forgot I was on a ship. Sail-away from the top deck was the best moment of the year." },
    { name: "Joel, Manila 🇵🇭", role: "Galley cook", text: "Advice for new crew: respect your roommate's sleep, learn everyone's name in your section, and never be late for all aboard. The sea rewards discipline." },
  ],
},

id: {
  ui: {
    navShips: "Kapal", navAcademy: "Akademi", navCommunity: "Komunitas",
    chipShips: "🚢 Kapal & cruise line", chipItin: "🗺 Perencana itinerary", chipCommunity: "🤝 Komunitas",
    shipsTitle: "🚢 Cruise Line & Kapal",
    shipsLead: "Siapa berlayar ke mana — cruise line besar dan kapal-kapal terkenalnya.",
    linesTitle: "Cruise line besar",
    fleetTitle: "Kapal terkenal",
    shipSearchPh: "Cari kapal atau cruise line…",
    thShip: "Kapal", thLine: "Cruise line", thYear: "Tahun", thGT: "Tonase kotor",
    thGuests: "Tamu", thRegion: "Wilayah umum",
    shipsNote: "Angka bersifat perkiraan (tamu pada okupansi ganda). Kapal berpindah wilayah sesuai musim — cek situs resmi untuk penempatan terkini.",
    shipsNone: "Kapal tidak ditemukan.",
    itinTitle: "🗺 Itinerariku",
    itinLead: "Susun rencana harianmu sendiri — pelabuhan, jam tiba, dan jam all aboard. Tersimpan di perangkat ini.",
    itPort: "Pelabuhan", itDate: "Tanggal", itArr: "Tiba", itDep: "All aboard", itNotes: "Catatan",
    itPortPh: "mis. Benoa, Bali", itNotesPh: "excursion, titik kumpul…",
    itAdd: "Tambah persinggahan", itEmpty: "Belum ada persinggahan — tambah pelabuhan pertamamu di atas.",
    itDay: "Hari",
    acGlossary: "📖 Glosarium", acQuiz: "🎓 Kuis",
    academyTitle: "🎓 Akademi",
    communityTitle: "🤝 Komunitas",
    communityLead: "Kamu tidak berlayar sendirian. Gabung komunitas World Cruise Academy.",
    joinTitle: "Gabung obrolan",
    joinWhatsApp: "Grup WhatsApp", joinWhatsAppDesc: "Obrolan harian kru & pecinta kapal pesiar",
    joinTelegram: "Channel Telegram", joinTelegramDesc: "Berita, tips, dan info lowongan",
    joinFacebook: "Grup Facebook", joinFacebookDesc: "Foto, cerita, dan tanya jawab",
    joinSoon: "Tautan segera hadir",
    storiesTitle: "Cerita dari lautan",
    sampleTag: "Contoh cerita",
    shareTitle: "Bagikan ceritamu",
    shareDesc: "Pernah kerja di kapal? Berlayar ke tempat tak terlupakan? Kirim ceritamu — mungkin kami tampilkan di sini.",
    shareBtn: "✉️ Kirim ceritamu",
  },
  regions: {
    caribbean: "Karibia", mediterranean: "Mediterania", europe: "Eropa Utara",
    asia: "Asia", alaska: "Alaska", bahamas: "Bahama & Florida", world: "Pelayaran dunia",
  },
  lines: [
    { key: "rci", blurb: "Kapal-kapal terbesar di dunia — raksasa bergaya resor kelas Oasis dan Icon.", regions: ["caribbean", "mediterranean"] },
    { key: "carnival", blurb: "'Fun Ships' — pelayaran santai dan meriah, besar di Amerika Utara.", regions: ["caribbean", "bahamas"] },
    { key: "msc", blurb: "Cruise line Eropa yang tumbuh pesat, armada modern, kuat di Mediterania dan Teluk.", regions: ["mediterranean", "caribbean"] },
    { key: "ncl", blurb: "Freestyle cruising — tanpa jam makan tetap, suasana resor.", regions: ["caribbean", "europe", "alaska"] },
    { key: "princess", blurb: "Pelayaran premium klasik, terkenal untuk musim Alaska.", regions: ["alaska", "caribbean", "world"] },
    { key: "celebrity", blurb: "Lini premium modern dengan kapal kelas Edge yang berdesain maju.", regions: ["caribbean", "mediterranean", "alaska"] },
    { key: "costa", blurb: "Gaya Italia di lautan — pusatnya di Mediterania.", regions: ["mediterranean"] },
    { key: "disney", blurb: "Pelayaran keluarga dengan keajaiban karakter Disney di kapal.", regions: ["bahamas", "caribbean"] },
    { key: "cunard", blurb: "Tradisi kapal samudra — penyeberangan transatlantik dan pelayaran dunia.", regions: ["world", "europe"] },
  ],
  stories: [
    { name: "Made, Bali 🇮🇩", role: "Bar waiter, 6 kontrak", text: "Kontrak pertama saya takut sekali dengan drill dan tes bahasa Inggris. Di kontrak ketiga, saya yang melatih kru baru. Kerja di kapal itu berat — tapi dari tabungan saya bisa bangun rumah, dan sudah melihat 41 negara." },
    { name: "Sarah, Manchester 🇬🇧", role: "Tamu pertama kali", text: "Saya hampir batal karena takut mabuk laut. Kabin tengah kapal, koyo dipasang lebih awal, dan sejujurnya — saya lupa sedang di atas kapal. Sail-away dari dek atas adalah momen terbaik tahun ini." },
    { name: "Joel, Manila 🇵🇭", role: "Juru masak galley", text: "Saran untuk kru baru: hargai jam tidur teman sekamar, hafalkan nama semua orang di seksimu, dan jangan pernah telat all aboard. Laut menghargai kedisiplinan." },
  ],
},
};

// Language-neutral data
const LINE_NAMES = {
  rci: "Royal Caribbean", carnival: "Carnival", msc: "MSC Cruises", ncl: "Norwegian",
  princess: "Princess", celebrity: "Celebrity", costa: "Costa", disney: "Disney Cruise Line",
  cunard: "Cunard",
};

// [line, ship, year, gross tonnage (approx), guests (approx), region]
const SHIPS = [
  ["rci", "Icon of the Seas", 2024, 250800, 5610, "caribbean"],
  ["rci", "Utopia of the Seas", 2024, 236860, 5668, "bahamas"],
  ["rci", "Wonder of the Seas", 2022, 236857, 5734, "caribbean"],
  ["rci", "Symphony of the Seas", 2018, 228081, 5518, "caribbean"],
  ["rci", "Harmony of the Seas", 2016, 226963, 5479, "caribbean"],
  ["rci", "Oasis of the Seas", 2009, 226838, 5602, "caribbean"],
  ["carnival", "Carnival Jubilee", 2023, 183521, 5374, "caribbean"],
  ["carnival", "Carnival Celebration", 2022, 183521, 5374, "caribbean"],
  ["carnival", "Mardi Gras", 2021, 181808, 5282, "caribbean"],
  ["msc", "MSC World America", 2025, 216638, 6762, "caribbean"],
  ["msc", "MSC World Europa", 2022, 215863, 6762, "mediterranean"],
  ["msc", "MSC Euribia", 2023, 184011, 5632, "europe"],
  ["msc", "MSC Virtuosa", 2021, 181541, 6334, "mediterranean"],
  ["ncl", "Norwegian Aqua", 2025, 156300, 3571, "caribbean"],
  ["ncl", "Norwegian Viva", 2023, 142500, 3099, "mediterranean"],
  ["ncl", "Norwegian Prima", 2022, 142500, 3099, "europe"],
  ["ncl", "Norwegian Encore", 2019, 169116, 3998, "alaska"],
  ["princess", "Star Princess", 2025, 175500, 4300, "caribbean"],
  ["princess", "Sun Princess", 2024, 175500, 4300, "mediterranean"],
  ["princess", "Discovery Princess", 2022, 145281, 3660, "alaska"],
  ["celebrity", "Celebrity Ascent", 2023, 140600, 3260, "caribbean"],
  ["celebrity", "Celebrity Beyond", 2022, 140600, 3260, "caribbean"],
  ["celebrity", "Celebrity Apex", 2020, 130818, 2910, "mediterranean"],
  ["costa", "Costa Smeralda", 2019, 185010, 5224, "mediterranean"],
  ["costa", "Costa Toscana", 2021, 185010, 5224, "mediterranean"],
  ["disney", "Disney Treasure", 2024, 144000, 4000, "caribbean"],
  ["disney", "Disney Wish", 2022, 144000, 4000, "bahamas"],
  ["disney", "Disney Fantasy", 2012, 129750, 4000, "caribbean"],
  ["cunard", "Queen Mary 2", 2004, 148528, 2691, "world"],
];
